# Generated by Django 4.1.5 on 2023-08-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40)),
                ('abbr_name', models.CharField(default=None, max_length=5)),
                ('division_ind', models.CharField(choices=[('E', 'East'), ('W', 'West')], default='E', max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('date_founded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
