# Generated by Django 4.1.5 on 2023-12-08 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0003_player_is_registered'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJoinPlayer',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'player')},
            },
        ),
    ]
