# Generated by Django 4.1.5 on 2023-09-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField(verbose_name='YYYY-MM-DD')),
                ('start_time', models.TimeField(verbose_name='HH:MM:SS')),
                ('est_duration', models.DurationField()),
                ('street_number', models.PositiveIntegerField(default=1295)),
                ('street_name', models.TextField(default='Williams Pkwy')),
                ('city', models.TextField(default='Brampton')),
            ],
        ),
    ]
