# Generated by Django 4.1.5 on 2023-09-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='est_duration',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='11:59:59', verbose_name='HH:MM:SS'),
        ),
    ]
