# Generated by Django 4.1.5 on 2023-09-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_est_duration_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='HH:MM:SS'),
        ),
    ]
