# Generated by Django 4.1.5 on 2023-08-12 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField(default=2023)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 8, 12, 1, 29, 46, 278397, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField(default=None)),
                ('champions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_def_first_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_first_award1', to='players.player')),
                ('all_def_first_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_first_award2', to='players.player')),
                ('all_def_first_3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_first_award3', to='players.player')),
                ('all_def_second_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_second_award1', to='players.player')),
                ('all_def_second_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_second_award2', to='players.player')),
                ('all_def_second_3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_second_award3', to='players.player')),
                ('all_def_third_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_third_award1', to='players.player')),
                ('all_def_third_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_third_award2', to='players.player')),
                ('all_def_third_3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_def_third_award3', to='players.player')),
                ('all_off_first_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_first_award1', to='players.player')),
                ('all_off_first_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_first_award2', to='players.player')),
                ('all_off_first_3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_first_award3', to='players.player')),
                ('all_off_second_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_second_award1', to='players.player')),
                ('all_off_second_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_second_award2', to='players.player')),
                ('all_off_second_3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_second_award3', to='players.player')),
                ('all_off_third_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_third_award1', to='players.player')),
                ('all_off_third_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_third_award2', to='players.player')),
                ('all_off_third_3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_off_third_award3', to='players.player')),
                ('amvp', models.ForeignKey(default=None, help_text='All-Star MVP', on_delete=django.db.models.deletion.CASCADE, related_name='amvp_award', to='players.player')),
                ('dpoy', models.ForeignKey(default=None, help_text='Defensive Player of the Year', on_delete=django.db.models.deletion.CASCADE, related_name='dpoy_award', to='players.player')),
                ('fourth_moty', models.ForeignKey(default=None, help_text='Fourth Man of the Year', on_delete=django.db.models.deletion.CASCADE, related_name='fourth_moty_award', to='players.player')),
                ('mdp', models.ForeignKey(default=None, help_text='Most Disrespected Player', on_delete=django.db.models.deletion.CASCADE, related_name='mdp_award', to='players.player')),
                ('mvp', models.ForeignKey(default=None, help_text='Most Valuable Player', on_delete=django.db.models.deletion.CASCADE, related_name='mvp_award', to='players.player')),
                ('roty', models.ForeignKey(default=None, help_text='Rookie of the Year', on_delete=django.db.models.deletion.CASCADE, related_name='roty_award', to='players.player')),
                ('season', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
        ),
    ]
