# Generated by Django 4.1.5 on 2023-08-10 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_rename_created_on_team_date_founded_team_abbr_name'),
        ('players', '0003_remove_player_weight_lbs_player_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2023)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=None, validators=[django.core.validators.MinValueValidator(models.DateTimeField(default=django.utils.timezone.now))])),
                ('AMVP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_AMVP', to='players.player')),
                ('All_Def_First_01', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_1st_01', to='players.player')),
                ('All_Def_First_02', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_1st_02', to='players.player')),
                ('All_Def_First_03', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_1st_03', to='players.player')),
                ('All_Def_Second_01', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_2nd_01', to='players.player')),
                ('All_Def_Second_02', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_2nd_02', to='players.player')),
                ('All_Def_Second_03', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_2nd_03', to='players.player')),
                ('All_Def_Third_01', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_3rd_01', to='players.player')),
                ('All_Def_Third_02', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_3rd_02', to='players.player')),
                ('All_Def_Third_03', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Def_3rd_03', to='players.player')),
                ('All_Off_First_01', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_1st_01', to='players.player')),
                ('All_Off_First_02', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_1st_02', to='players.player')),
                ('All_Off_First_03', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_1st_03', to='players.player')),
                ('All_Off_Second_01', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_2nd_01', to='players.player')),
                ('All_Off_Second_02', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_2nd_02', to='players.player')),
                ('All_Off_Second_03', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_2nd_03', to='players.player')),
                ('All_Off_Third_01', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_3rd_01', to='players.player')),
                ('All_Off_Third_02', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_3rd_02', to='players.player')),
                ('All_Off_Third_03', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_All_Off_3rd_03', to='players.player')),
                ('DPOY', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_DPOY', to='players.player')),
                ('FourthMOTY', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_4MOTY', to='players.player')),
                ('MDP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_MDP', to='players.player')),
                ('MVP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_MVP', to='players.player')),
                ('ROTY', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_ROTY', to='players.player')),
                ('champions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
