# Generated by Django 4.1.5 on 2023-08-12 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='champions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 18, 23, 10, 631162, tzinfo=datetime.timezone.utc)),
        ),
    ]
