# Generated by Django 4.1.5 on 2023-08-10 15:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='AMVP',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_First_01',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_First_02',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_First_03',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_Second_01',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_Second_02',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_Second_03',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_Third_01',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_Third_02',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Def_Third_03',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_First_01',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_First_02',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_First_03',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_Second_01',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_Second_02',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_Second_03',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_Third_01',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_Third_02',
        ),
        migrations.RemoveField(
            model_name='season',
            name='All_Off_Third_03',
        ),
        migrations.RemoveField(
            model_name='season',
            name='DPOY',
        ),
        migrations.RemoveField(
            model_name='season',
            name='FourthMOTY',
        ),
        migrations.RemoveField(
            model_name='season',
            name='MDP',
        ),
        migrations.RemoveField(
            model_name='season',
            name='MVP',
        ),
        migrations.RemoveField(
            model_name='season',
            name='ROTY',
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=None, null=True, validators=[django.core.validators.MinValueValidator(models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 46, 44, 725721, tzinfo=datetime.timezone.utc)))]),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 46, 44, 725721, tzinfo=datetime.timezone.utc)),
        ),
    ]
