# Generated by Django 4.1.5 on 2023-08-12 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 1, 11, 41, 854806, tzinfo=datetime.timezone.utc)),
        ),
    ]
