# Generated by Django 4.1.5 on 2023-08-12 01:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_created_on_team_date_founded_team_abbr_name'),
        ('seasons', '0002_remove_season_amvp_remove_season_all_def_first_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='champions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=None, null=True, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
