# Generated by Django 4.1.5 on 2023-08-14 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_alter_season_champions_alter_season_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 18, 13, 9, 372627, tzinfo=datetime.timezone.utc)),
        ),
    ]
