# Generated by Django 4.1.5 on 2023-08-14 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_season_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 18, 21, 43, 817456, tzinfo=datetime.timezone.utc)),
        ),
    ]
