# Generated by Django 4.1.5 on 2023-09-11 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0004_alter_season_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 20, 10, 33, 968669, tzinfo=datetime.timezone.utc)),
        ),
    ]
