# Generated by Django 4.1.5 on 2023-09-30 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0008_alter_season_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 18, 15, 6, 93380, tzinfo=datetime.timezone.utc)),
        ),
    ]
