# Generated by Django 4.1.5 on 2023-10-02 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0009_alter_season_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 2, 2, 46, 920859, tzinfo=datetime.timezone.utc)),
        ),
    ]
