# Generated by Django 4.1.5 on 2023-12-08 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0014_alter_season_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 5, 33, 54, 362606, tzinfo=datetime.timezone.utc)),
        ),
    ]
