# Generated by Django 4.1.5 on 2023-06-25 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first', models.CharField(max_length=255)),
                ('player_last', models.CharField(max_length=255)),
                ('player_height_in', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(0)])),
                ('player_height_ft', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(0)])),
                ('origin', models.CharField(max_length=255)),
            ],
        ),
    ]
