# Generated by Django 4.1.5 on 2023-06-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_player_player_height_ft_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='NewPlayer',
        ),
    ]
