# Generated by Django 4.1.5 on 2023-06-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_player_newplayer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPlayer',
            new_name='Player',
        ),
    ]
