# Generated by Django 4.1.5 on 2023-06-26 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_newplayer_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(default=23),
        ),
        migrations.AddField(
            model_name='player',
            name='player_weight_kgs',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='player',
            name='player_weight_lbs',
            field=models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
