# Generated by Django 4.1.5 on 2023-02-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_firstname', models.CharField(max_length=40)),
                ('player_lastname', models.CharField(max_length=40)),
                ('player_height_in', models.IntegerField(default=0)),
                ('player_height_ft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40)),
            ],
        ),
    ]
