# Generated by Django 4.1.5 on 2023-02-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_height_ft',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_height_in',
            field=models.IntegerField(default=5),
        ),
    ]
