# Generated by Django 4.1.5 on 2023-02-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_season_player_part_of_team_player_player_paid_ind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_paid_ind',
            new_name='player_paid',
        ),
    ]
