# Generated by Django 4.1.5 on 2023-02-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_seasonteamplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division_ind',
            field=models.CharField(choices=[('E', 'East'), ('W', 'West')], default='E', max_length=1),
        ),
    ]
