# Generated by Django 4.1.5 on 2023-02-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_teamstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamStats',
            new_name='TeamStat',
        ),
    ]
