# Generated by Django 4.1.5 on 2023-02-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_teamstats_teamstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonteamplayer',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='seasonteamplayer',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='seasonteamplayer',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='teamstat',
            old_name='team_id',
            new_name='team',
        ),
    ]
