# Generated by Django 4.1.5 on 2023-02-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_player_id_seasonteamplayer_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstat',
            name='season',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.season'),
        ),
    ]
