# Generated by Django 4.1.5 on 2023-02-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_teamstat_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstat',
            name='ties',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_height_ft',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_height_in',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='teamstat',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstat',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
