# Generated by Django 4.1.5 on 2023-02-16 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_teamstat_ties_alter_player_player_height_ft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('game', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_date', models.DateField(help_text='YYYY-MM-DD')),
                ('lose_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='losing_team', to='home.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.season')),
                ('win_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winning_team', to='home.team')),
            ],
        ),
    ]
