# Generated by Django 4.1.5 on 2023-02-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_game_game_id_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='blocks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='rebounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='steals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
