# Generated by Django 4.1.5 on 2023-02-16 01:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_gamestat_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamestat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.game'),
        ),
    ]
