# Generated by Django 4.1.5 on 2023-02-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_gamestat_id_alter_gamestat_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonTeamPlayer',
            new_name='STP',
        ),
    ]
