# Generated by Django 4.1.5 on 2023-02-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_seasonteamplayer_stp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_paid',
            new_name='is_registered',
        ),
    ]
