# Generated by Django 4.1.5 on 2023-02-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_player_paid_player_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='part_of_team',
        ),
    ]
