# Generated by Django 4.1.5 on 2023-03-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_player_part_of_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamStat',
        ),
    ]
