# Generated by Django 4.1.5 on 2023-08-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(default='', max_length=6)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_on', models.DateField(verbose_name='YYYY-MM-DD')),
                ('lose_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='losing_team', to='teams.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.season')),
                ('win_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winning_team', to='teams.team')),
            ],
        ),
    ]
