# Generated by Django 4.1.5 on 2023-09-21 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
        ('events', '0003_alter_event_end_time'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='lose_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='played_on',
        ),
        migrations.RemoveField(
            model_name='game',
            name='win_team',
        ),
        migrations.AddField(
            model_name='game',
            name='away_player_01',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_01', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_player_02',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_02', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_player_03',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_03', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_player_04',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_04', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_player_05',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_05', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_player_01',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_01', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_player_02',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_02', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_player_03',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_03', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_player_04',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_04', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_player_05',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_05', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='teams.team'),
        ),
    ]
