# Generated by Django 4.1.5 on 2023-10-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0002_remove_game_lose_team_remove_game_played_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_player_01',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_01', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_player_02',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_02', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_player_03',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_03', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_player_04',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_04', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_player_05',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_player_05', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_player_01',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_01', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_player_02',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_02', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_player_03',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_03', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_player_04',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_04', to='players.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_player_05',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_player_05', to='players.player'),
        ),
    ]
