# Generated by Django 4.1.5 on 2023-10-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_end_time'),
        ('games', '0003_alter_game_away_player_01_alter_game_away_player_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
