# Generated by Django 4.1.5 on 2023-08-07 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_origin_player_weight_lbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='weight_lbs',
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=150, help_text='Weight in lbs', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
